# Generated by Django 4.0.2 on 2023-02-13 15:41

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
       migrations.RunSQL(
         sql = ( f"DO $do$ "
                 f"BEGIN "
                 f"  IF NOT EXISTS ( "
                 f"     SELECT FROM pg_catalog.pg_roles WHERE rolname='desi' "
                 f"  ) THEN "
                 f"     CREATE ROLE desi PASSWORD '{os.getenv('DESIPASSWORD')}' LOGIN; "
                 f"  END IF; "
                 f"END "
                 f"$do$;" ),
         reverse_sql = ""
       ),
       migrations.RunSQL( 
         sql = 'CREATE SCHEMA IF NOT EXISTS iron',
         reverse_sql = 'DROP SCHEMA IF EXISTS iron'
       ),
       migrations.RunSQL(
         sql = 'GRANT USAGE ON SCHEMA iron TO desi',
         reverse_sql = 'REVOKE USAGE ON SCHEMA iron FROM desi'
       ),
       migrations.RunSQL(
         sql = ( 'ALTER DEFAULT PRIVILEGES IN SCHEMA iron '
                 'GRANT SELECT ON TABLES TO desi' ),
         reverse_sql = ( 'ALTER DEFAULT PRIVILEGES IN SCHEMA iron '
                         'REVOKE SELECT ON TABLES FROM desi' )
      )
    ]
