version: "3.2"

# This file is really set up for Rob on his desktop....
# (Moslty that shows up in the source of the /data bind mount.)

services:
  desidb-django-postgres:
    image: rknop/postgres-q3c
    volumes:
      - desidb-django-postgresdata:/var/lib/postgresql/data
      - type: bind
        source: /home/raknop/secrets
        target: /secrets
    environment:
      - POSTGRES_NAME=desidb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=""
      - POSTGRES_PASSWORD=${POSTGRESPASSWORD}

  desidb-django:
    image: rknop/desidb-django
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=desidb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/secrets/desidb_admin_postgres_password
      - DESIPASSWORD=${DESIPASSWORD}
    user: "${UID}:${GID}"
    volumes:
      - type: bind
        source: ./django
        target: /django
      - type: bind
        source: /data/raknop/desi
        target: /data
      - type: bind
        source: /home/raknop/secrets
        target: /secrets

volumes:
  desidb-django-postgresdata:
