# Generated by Django 4.0.2 on 2022-04-02 13:46

import db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryTargets',
            fields=[
                ('dbid', models.BigAutoField(primary_key=True, serialize=False)),
                ('catalog', models.TextField(null=True)),
                ('catver', models.TextField(null=True)),
                ('whenobs', models.TextField(null=True)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('pmra', db.models.RealField(null=True)),
                ('pmdec', db.models.RealField(null=True)),
                ('ref_epoch', db.models.RealField(null=True)),
                ('override', models.BooleanField(null=True)),
                ('flux_g', db.models.RealField(null=True)),
                ('flux_r', db.models.RealField(null=True)),
                ('flux_z', db.models.RealField(null=True)),
                ('parallax', db.models.RealField(null=True)),
                ('targetid', models.BigIntegerField(null=True)),
                ('desi_target', models.BigIntegerField(null=True)),
                ('scnd_target', models.BigIntegerField(null=True)),
                ('scnd_order', models.IntegerField(null=True)),
                ('subpriority', models.FloatField(null=True)),
                ('obsconditions', models.BigIntegerField(null=True)),
                ('priority_init', models.BigIntegerField(null=True)),
                ('numobs_init', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': '"general"."secondarytargets"',
            },
        ),
        migrations.CreateModel(
            name='TargetFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
            ],
            options={
                'db_table': 'general"."targetfiles',
            },
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('targetid', models.BigIntegerField()),
                ('whenobs', models.TextField(null=True)),
                ('survey', models.TextField(null=True)),
                ('release', models.SmallIntegerField(null=True)),
                ('brickid', models.IntegerField(null=True)),
                ('brickname', models.CharField(max_length=8, null=True)),
                ('brick_objid', models.IntegerField(null=True)),
                ('morphtype', models.CharField(max_length=4, null=True)),
                ('ra', models.FloatField()),
                ('ra_ivar', db.models.RealField(null=True)),
                ('dec', models.FloatField()),
                ('dec_ivar', db.models.RealField(null=True)),
                ('flux_g', db.models.RealField(null=True)),
                ('flux_r', db.models.RealField(null=True)),
                ('flux_z', db.models.RealField(null=True)),
                ('flux_ivar_g', db.models.RealField(null=True)),
                ('flux_ivar_r', db.models.RealField(null=True)),
                ('flux_ivar_z', db.models.RealField(null=True)),
                ('shape_r', db.models.RealField(null=True)),
                ('shape_e1', db.models.RealField(null=True)),
                ('shape_e2', db.models.RealField(null=True)),
                ('shape_r_ivar', db.models.RealField(null=True)),
                ('shape_e1_ivar', db.models.RealField(null=True)),
                ('shape_e2_ivar', db.models.RealField(null=True)),
                ('sersic', db.models.RealField(null=True)),
                ('sersic_ivar', db.models.RealField(null=True)),
                ('ref_id', models.BigIntegerField(null=True)),
                ('ref_cat', models.CharField(max_length=2, null=True)),
                ('parallax', db.models.RealField(null=True)),
                ('parallax_ivar', db.models.RealField(null=True)),
                ('pmra', db.models.RealField(null=True)),
                ('pmra_ivar', db.models.RealField(null=True)),
                ('pmdec', db.models.RealField(null=True)),
                ('pmdec_ivar', db.models.RealField(null=True)),
                ('photsys', models.CharField(max_length=1, null=True)),
                ('desi_target', models.BigIntegerField(null=True)),
                ('bgs_target', models.BigIntegerField(null=True)),
                ('mws_target', models.BigIntegerField(null=True)),
                ('subpriority', models.FloatField(null=True)),
                ('obsconditions', models.BigIntegerField(null=True)),
                ('priority_init', models.BigIntegerField(null=True)),
                ('numobs_init', models.BigIntegerField(null=True)),
                ('scnd_target', models.BigIntegerField(null=True)),
                ('hpxpixel', models.BigIntegerField(null=True)),
                ('targetfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.targetfiles')),
            ],
            options={
                'db_table': 'general"."maintargets',
            },
        ),
        migrations.AddConstraint(
            model_name='targetfiles',
            constraint=models.UniqueConstraint(fields=('filename',), name='unique_targetfiles'),
        ),
        migrations.AddField(
            model_name='secondarytargets',
            name='targetfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.targetfiles'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['targetid'], name='idx_targets_targetid'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['survey'], name='idx_targets_survey'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['desi_target'], name='idx_targets_desi_target'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['bgs_target'], name='idx_targets_bgs_target'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['mws_target'], name='idx_targets_mws_target'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['scnd_target'], name='idx_targets_scnd_target'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(fields=['hpxpixel'], name='idx_targets_hpxpixel'),
        ),
        migrations.AddIndex(
            model_name='targets',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'dec'), name='idx_targets_q3c'),
        ),
        migrations.AlterUniqueTogether(
            name='targets',
            unique_together={('targetid', 'whenobs', 'survey')},
        ),
        migrations.AddIndex(
            model_name='secondarytargets',
            index=db.models.LongNameBTreeIndex(fields=['catalog', 'catver', 'whenobs'], name='idx_secondarytargets_direc'),
        ),
        migrations.AddIndex(
            model_name='secondarytargets',
            index=db.models.LongNameBTreeIndex(fields=['targetid'], name='idx_secondarytargets_targetid'),
        ),
        migrations.AddIndex(
            model_name='secondarytargets',
            index=db.models.LongNameBTreeIndex(fields=['desi_target'], name='idx_secondarytargets_desi_target'),
        ),
        migrations.AddIndex(
            model_name='secondarytargets',
            index=db.models.LongNameBTreeIndex(fields=['scnd_target'], name='idx_secondarytargets_scnd_target'),
        ),
        migrations.AddIndex(
            model_name='secondarytargets',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'dec'), name='idx_secondarytargets_q3c'),
        ),
        migrations.AlterUniqueTogether(
            name='secondarytargets',
            unique_together={('catalog', 'catver', 'targetid')},
        ),
    ]
