# Generated by Django 4.0.2 on 2022-04-02 14:05

import db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Targets',
            new_name='MainTargets',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_targetid',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_survey',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_desi_target',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_bgs_target',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_mws_target',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_scnd_target',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_hpxpixel',
        ),
        migrations.RemoveIndex(
            model_name='maintargets',
            name='idx_targets_q3c',
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['targetid'], name='idx_maintargets_targetid'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['survey'], name='idx_maintargets_survey'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['desi_target'], name='idx_maintargets_desi_target'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['bgs_target'], name='idx_maintargets_bgs_target'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['mws_target'], name='idx_maintargets_mws_target'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['scnd_target'], name='idx_maintargets_scnd_target'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(fields=['hpxpixel'], name='idx_maintargets_hpxpixel'),
        ),
        migrations.AddIndex(
            model_name='maintargets',
            index=db.models.LongNameBTreeIndex(db.models.q3c_ang2ipix('ra', 'dec'), name='idx_maintargets_q3c'),
        ),
    ]
