# Generated by Django 5.2.9 on 2025-12-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healpixfibermap',
            name='desiname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='healpixfibermap',
            name='max_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='healpixfibermap',
            name='mean_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='healpixfibermap',
            name='min_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='healpixredshifts',
            name='fitmethod',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='desiname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='firstnight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='lastnight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='max_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='mean_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='min_mjd',
            field=models.FloatField(null=True),
        ),
    ]
