# Generated by Django 5.2.9 on 2025-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loa', '0002_healpixfibermap_desiname_healpixfibermap_max_mjd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesredshifts',
            name='fitmethod',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
