# Generated by Django 4.0.2 on 2022-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativetiles',
            name='filename',
            field=models.TextField(default=''),
        ),
    ]
