# Generated by Django 4.0.2 on 2023-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_cumulativetiles_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesfibermap',
            name='firstnight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='lastnight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='max_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='mean_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='min_mjd',
            field=models.FloatField(null=True),
        ),
    ]
