# Generated by Django 4.0.2 on 2023-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_tilesfibermap_firstnight_tilesfibermap_lastnight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesexpfibermap',
            name='in_coadd_b',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tilesexpfibermap',
            name='in_coadd_r',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tilesexpfibermap',
            name='in_coadd_z',
            field=models.BooleanField(null=True),
        ),
    ]
