# Generated by Django 4.0.2 on 2024-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_tilesexpfibermap_in_coadd_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesfibermap',
            name='desiname',
            field=models.TextField(null=True),
        ),
    ]
