# Generated by Django 4.0.2 on 2024-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_tilesfibermap_desiname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilesfibermap',
            name='desiname',
            field=models.CharField(max_length=22, null=True),
        ),
    ]
