# Generated by Django 4.0.2 on 2024-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_alter_tilesfibermap_desiname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesredshifts',
            name='fitmethod',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
