# Generated by Django 4.0.2 on 2024-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilesfibermap',
            name='desiname',
            field=models.TextField(null=True),
        ),
    ]
