# Generated by Django 4.0.2 on 2024-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jura', '0003_healpix_healpixtsnr2_healpixredshifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healpixfibermap',
            name='desiname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='healpixfibermap',
            name='max_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='healpixfibermap',
            name='mean_mjd',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='healpixfibermap',
            name='min_mjd',
            field=models.FloatField(null=True),
        ),
    ]
