# Generated by Django 4.0.2 on 2024-09-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jura', '0004_healpixfibermap_desiname_healpixfibermap_max_mjd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healpixredshifts',
            name='fitmethod',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
