CREATE SCHEMA IF NOT EXISTS general AUTHORIZATION postgres;
GRANT USAGE ON SCHEMA general TO desi;
ALTER DEFAULT PRIVILEGES IN SCHEMA general GRANT SELECT ON TABLES TO desi;

CREATE TABLE general.targetfiles(
  id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  filename text NOT NULL
);
CREATE UNIQUE INDEX idx_targetfiles_filename ON general.targetfiles( filename );


CREATE TABLE general.maintargets(
  id                                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  release                           smallint,
  brickid                           integer,
  brickname                         varchar[8],
  brick_objid                       integer,
  morphtype                         varchar[4],
  ra                                double precision NOT NULL,
  ra_ivar                           real,
  dec                               double precision NOT NULL,
  dec_ivar                          real,
  dchisq                            real[5],
  ebv                               real,
  flux_g                            real,
  flux_r                            real,
  flux_z                            real,
  flux_ivar_g                       real,
  flux_ivar_r                       real,
  flux_ivar_z                       real,
  mw_transmission_g                 real,
  mw_transmission_r                 real,
  mw_transmission_z                 real,
  fracflux_g                        real,
  fracflux_r                        real,
  fracflux_z                        real,
  fracmasked_g                      real,
  fracmasked_r                      real,
  fracmasked_z                      real,
  fracin_g                          real,
  fracin_r                          real,
  fracin_z                          real,
  nobs_g                            smallint,
  nobs_r                            smallint,
  nobs_z                            smallint,
  psfdepth_g                        real,
  psfdepth_r                        real,
  psfdepth_z                        real,
  galdepth_g                        real,
  galdepth_r                        real,
  galdepth_z                        real,
  flux_w1                           real,
  flux_w2                           real,
  flux_w3                           real,
  flux_w4                           real,
  flux_ivar_w1                      real,
  flux_ivar_w2                      real,
  flux_ivar_w3                      real,
  flux_ivar_w4                      real,
  mw_transmission_w1                real,
  mw_transmission_w2                real,
  mw_transmission_w3                real,
  mw_transmission_w4                real,
  allmask_g                         smallint,
  allmask_r                         smallint,
  allmask_z                         smallint,
  fiberflux_g                       real,
  fiberflux_r                       real,
  fiberflux_z                       real,
  fibertotflux_g                    real,
  fibertotflux_r                    real,
  fibertotflux_z                    real,
  ref_epoch                         real,
  wisemask_w1                       smallint,
  wisemask_w2                       smallint,
  maskbits                          smallint,
  lc_flux_w1                        real[15],
  lc_flux_w2                        real[15],
  lc_flux_ivar_w1                   real[15],
  lc_flux_ivar_w2                   real[15],
  lc_nobs_w1                        smallint[15],
  lc_nobs_w2                        smallint[15],
  lc_mjd_w1                         double precision[15],
  lc_mjd_w2                         double precision[15],
  shape_r                           real,
  shape_e1                          real,
  shape_e2                          real,
  shape_r_ivar                      real,
  shape_e1_ivar                     real,
  shape_e2_ivar                     real,
  sersic                            real,
  sersic_ivar                       real,
  ref_id                            bigint,
  ref_cat                           varchar[2],
  gaia_phot_g_mean_mag              real,
  gaia_phot_g_mean_flux_over_error  real,
  gaia_phot_bp_mean_mag             real,
  gaia_phot_bp_mean_flux_over_error real,
  gaia_phot_rp_mean_mag             real,
  gaia_phot_rp_mean_flux_over_error real,
  gaia_phot_bp_rp_excess_factor     real,
  gaia_phot_bp_rp_excess_noise      real,
  gaia_duplicated_source            boolean,
  gaia_astrometric_sigma5d_max      real,
  gaia_astrometric_params_solved    boolean,
  gaia_astrometric_params_sovled    smallint,
  parallax                          real,
  parallax_ivar                     real,
  pmra                              real,
  pmra_ivar                         real,
  pmdec                             real,
  pmdec_ivar                        real,
  photsys                           varchar[1],
  targetid                          bigint NOT NULL,
  desi_target                       bigint,
  bgs_target                        bigint,
  mws_target                        bigint,
  subpriority                       double precision,
  obsconditions                     bigint,
  priority_init                     bigint,
  numobs_init                       bigint,
  scnd_target                       bigint,
  hpxpixel                          bigint,
  targetfile_id                     UUID NOT NULL
);
-- CREATE INDEX idx_maintargets_targetid ON general.maintargets( targetid );
CREATE UNIQUE INDEX idx_maintargets_unique ON general.maintargets( targetid );
CREATE INDEX idx_maintargets_desi ON general.maintargets( desi_target) ;
CREATE INDEX idx_maintargets_bgs ON general.maintargets( bgs_target );
CREATE INDEX idx_maintargets_mws ON general.maintargets( mws_target );
CREATE INDEX idx_maintargets_scnd ON general.maintargets( scnd_target );
CREATE INDEX idx_maintargets_hpxpixel ON general.maintargets( hpxpixel );
CREATE INDEX idx_maintargets_q3c ON general.maintargets( public.q3c_ang2ipix( ra, "dec" ) );
CREATE INDEX idx_maintargets_targetfile ON general.maintargets( targetfile_id );
ALTER TABLE general.maintargets ADD CONSTRAINT fk_maintargets_targetfile
  FOREIGN KEY( targetfile_id ) REFERENCES general.targetfiles( id ) ON DELETE RESTRICT;




CREATE TABLE general.sv3targets(
  id                                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  release                           smallint,
  brickid                           integer,
  brickname                         varchar[8],
  brick_objid                       integer,
  morphtype                         varchar[4],
  ra                                double precision NOT NULL,
  ra_ivar                           real,
  dec                               double precision NOT NULL,
  dec_ivar                          real,
  dchisq                            real[5],
  ebv                               real,
  flux_g                            real,
  flux_r                            real,
  flux_z                            real,
  flux_ivar_g                       real,
  flux_ivar_r                       real,
  flux_ivar_z                       real,
  mw_transmission_g                 real,
  mw_transmission_r                 real,
  mw_transmission_z                 real,
  fracflux_g                        real,
  fracflux_r                        real,
  fracflux_z                        real,
  fracmasked_g                      real,
  fracmasked_r                      real,
  fracmasked_z                      real,
  fracin_g                          real,
  fracin_r                          real,
  fracin_z                          real,
  nobs_g                            smallint,
  nobs_r                            smallint,
  nobs_z                            smallint,
  psfdepth_g                        real,
  psfdepth_r                        real,
  psfdepth_z                        real,
  galdepth_g                        real,
  galdepth_r                        real,
  galdepth_z                        real,
  flux_w1                           real,
  flux_w2                           real,
  flux_w3                           real,
  flux_w4                           real,
  flux_ivar_w1                      real,
  flux_ivar_w2                      real,
  flux_ivar_w3                      real,
  flux_ivar_w4                      real,
  mw_transmission_w1                real,
  mw_transmission_w2                real,
  mw_transmission_w3                real,
  mw_transmission_w4                real,
  allmask_g                         smallint,
  allmask_r                         smallint,
  allmask_z                         smallint,
  fiberflux_g                       real,
  fiberflux_r                       real,
  fiberflux_z                       real,
  fibertotflux_g                    real,
  fibertotflux_r                    real,
  fibertotflux_z                    real,
  ref_epoch                         real,
  wisemask_w1                       smallint,
  wisemask_w2                       smallint,
  maskbits                          smallint,
  lc_flux_w1                        real[15],
  lc_flux_w2                        real[15],
  lc_flux_ivar_w1                   real[15],
  lc_flux_ivar_w2                   real[15],
  lc_nobs_w1                        smallint[15],
  lc_nobs_w2                        smallint[15],
  lc_mjd_w1                         double precision[15],
  lc_mjd_w2                         double precision[15],
  shape_r                           real,
  shape_e1                          real,
  shape_e2                          real,
  shape_r_ivar                      real,
  shape_e1_ivar                     real,
  shape_e2_ivar                     real,
  sersic                            real,
  sersic_ivar                       real,
  ref_id                            bigint,
  ref_cat                           varchar[2],
  gaia_phot_g_mean_mag              real,
  gaia_phot_g_mean_flux_over_error  real,
  gaia_phot_bp_mean_mag             real,
  gaia_phot_bp_mean_flux_over_error real,
  gaia_phot_rp_mean_mag             real,
  gaia_phot_rp_mean_flux_over_error real,
  gaia_phot_bp_rp_excess_factor     real,
  gaia_phot_bp_rp_excess_noise      real,
  gaia_duplicated_source            boolean,
  gaia_astrometric_sigma5d_max      real,
  gaia_astrometric_params_solved    boolean,
  gaia_astrometric_params_sovled    smallint,
  parallax                          real,
  parallax_ivar                     real,
  pmra                              real,
  pmra_ivar                         real,
  pmdec                             real,
  pmdec_ivar                        real,
  photsys                           varchar[1],
  targetid                          bigint NOT NULL,
  sv3_desi_target                   bigint,
  sv3_bgs_target                    bigint,
  sv3_mws_target                    bigint,
  subpriority                       double precision,
  obsconditions                     bigint,
  priority_init                     bigint,
  numobs_init                       bigint,
  sv3_scnd_target                   bigint,
  hpxpixel                          bigint,
  targetfile_id                     UUID NOT NULL
);
-- CREATE INDEX idx_sv3targets_targetid ON general.sv3targets( targetid );
CREATE UNIQUE INDEX idx_sv3targets_targetid ON general.sv3targets( targetid );
CREATE INDEX idx_sv3targets_desi ON general.sv3targets( sv3_desi_target) ;
CREATE INDEX idx_sv3targets_bgs ON general.sv3targets( sv3_bgs_target );
CREATE INDEX idx_sv3targets_mws ON general.sv3targets( sv3_mws_target );
CREATE INDEX idx_sv3targets_scnd ON general.sv3targets( sv3_scnd_target );
CREATE INDEX idx_sv3targets_hpxpixel ON general.sv3targets( hpxpixel );
CREATE INDEX idx_sv3targets_q3c ON general.sv3targets( public.q3c_ang2ipix( ra, "dec" ) );
CREATE INDEX idx_sv3targets_targetfile ON general.sv3targets( targetfile_id );
ALTER TABLE general.sv3targets ADD CONSTRAINT fk_sv3targets_targetfile
  FOREIGN KEY( targetfile_id ) REFERENCES general.targetfiles( id ) ON DELETE RESTRICT;
