apiVersion: v1
data:
  desidb_admin_postgres_password: ejQ5dm82ZHdkODMzeGpwYQo=
  desidb_desi_postgres_password: NWtGaWJlcnMh
kind: Secret
metadata:
  name: desidb-secrets
  namespace: desidb
type: Opaque
