---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-desidb-desidb
  name: desidb
  namespace: desidb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-desidb-desidb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-desidb-desidb
    spec:
      containers:
      - env:
        - name: POSTGRES_NAME
          value: desidb
        - name: POSTGRES_PASSWORD_FILE
          value: /secrets/pgpasswd
        - name: POSTGRES_USER
          value: postgres
        - name: PYTHONPATH
          value: /desidb
        image: registry.nersc.gov/desi/rknop/desidb-shell:20251218
        imagePullPolicy: Always
        name: desidb
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        # Uncomment this next one to not actually run apache
        command: [ "tail", "-f", "/etc/issue" ]
        volumeMounts:
        - mountPath: /desidb
          name: desidb-code
        - mountPath: /secrets
          name: desidb-secrets
        - mountPath: /data
          name: desi-data
          readOnly: true
        - mountPath: /desicollab
          name: desi-collab
          readOnly: true
        - mountPath: /targets
          name: desi-targets
          readOnly: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-nersc
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 58102
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /global/cfs/cdirs/desi/users/raknop/desidb
          type: Directory
        name: desidb-code
      - name: desidb-secrets
        secret:
          defaultMode: 256
          optional: false
          secretName: desidb-secrets
      - hostPath:
          path: /global/cfs/cdirs/desi
          type: Directory
        name: desi-data
      - hostPath:
          path: /global/cfs/cdirs/desicollab
          type: Directory
        name: desi-collab
      - hostPath:
          path: /global/cfs/cdirs/desi/target
          type: Directory
        name: desi-targets
---
apiVersion: v1
kind: Service
metadata:
  name: desidb
  namespace: desidb
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-desidb-desidb
  sessionAffinity: None
  type: ClusterIP
---
