# Generated by Django 4.0.2 on 2022-02-15 18:13
# Manually edited by RKnop that same day

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
       migrations.RunSQL(
         sql = f"CREATE USER desi PASSWORD '{os.getenv('DESIPASSWORD')}' LOGIN",
         reverse_sql = "DROP USER desi"
       ),
       migrations.RunSQL( 
         sql = 'CREATE SCHEMA IF NOT EXISTS everest',
         reverse_sql = 'DROP SCHEMA IF EXISTS everest'
       ),
       migrations.RunSQL(
         sql = 'GRANT USAGE ON SCHEMA everest TO desi',
         reverse_sql = 'REVOKE USAGE ON SCHEMA everest FROM desi'
       ),
       migrations.RunSQL(
         sql = ( 'ALTER DEFAULT PRIVILEGES IN SCHEMA everest '
                 'GRANT SELECT ON TABLES TO desi' ),
         reverse_sql = ( 'ALTER DEFAULT PRIVILEGES IN SCHEMA everest '
                         'REVOKE SELECT ON TABLES FROM desi' )
      )
    ]
