# Generated by Django 4.0.2 on 2022-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuji', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesfibermap',
            name='sv3_bgs_target',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='sv3_desi_target',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='sv3_mws_target',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tilesfibermap',
            name='sv3_scnd_target',
            field=models.BigIntegerField(null=True),
        ),
    ]
